config/routes.rb
Donuts::Application.routes.draw do
  devise_for :users
  
  get "/users/current" => "users#current"
  get "/entries/current" => "entries#current"
  resources :entries
  get "/statistics" => "statistics#index"
  get "/statistics/:type" => "statistics#show"
  get "/users/:id/edit", to: "users#edit"
  get "/users/readme", to: "users#readme"
  put "/users/:id", to: "users#update"

  root :to => 'entries#index'

end

app/models/entry.rb
# == Schema Information
#
# Table name: entries
#
#  id                :integer          not null, primary key
#  content           :text
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  word_count        :integer
#  distraction_count :integer
#  duration          :integer
#  words_per_minute  :integer
#  user_id           :integer
#  goal_completed    :boolean
#

class Entry < ActiveRecord::Base
  include Statistics
  extend Searchable
  self.per_page = 10
  attr_accessible :content, :word_count, :distraction_count, :duration, :words_per_minute, :user_id, :goal_completed

  belongs_to :user
  has_many :tags

  after_save :find_and_save_tags

  validates_presence_of :content

  scope :user_entries, ->(user_id) { where("user_id = ?", user_id) }

  private
    #TODO add tags as an array datatype so we can avoid deletion everytime
    def find_and_save_tags
      self.tags.destroy_all
      self.content.scan(Tag::REGEX).flatten
        .each{ |tag_name| Tag.create(entry_id: self.id, name: tag_name) }
    end
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  entry_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tag < ActiveRecord::Base
  REGEX = /(?:\s|^|>)(?:#(?!\d+(?:\s|$)))([\w-]+)(?=\s|$|\.|\?|!|&|,|<)/i
  attr_accessible :entry_id, :name
  belongs_to :entries
  validates :name, :uniqueness => {:scope => :entry_id}
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  goal_duration          :integer
#  goal_word_count        :integer
#  bg_color_hex           :string(255)
#  font_color_hex         :string(255)
#  font_point             :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :bg_color_hex, :font_color_hex, :font_point, :goal_duration, :goal_word_count, :distraction_timeout

  has_many :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  # GET /entries
  # GET /entries.json
  def index
    if params[:search].blank?
      @entries = Entry.where(user_id: current_user.id).order("created_at desc")
    else
      @search = params[:search]
      @entries = Entry.search(params[:search], current_user.id)
    end

    respond_to do |format|
      format.html { @entries = @entries.blank? ? @entries : @entries.page(params[:page]) }
      format.js { @entries = @entries.blank? ? @entries : @entries.page(params[:page]) }
      format.download_html { send_data format_as_html(@entries), filename: "entries.html" }
      format.download_text { send_data format_as_text(@entries), filename: "entries.txt" }
    end
  end
  
  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/current
  def current
    entry = Entry.where("cast(created_at as text) like ? AND user_id = ?", "#{Time.zone.today}%", current_user.id).first
    render json: entry
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(params[:entry])

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entries_path, notice: 'Entry was successfully created.' }
        format.json { render json: @entry, status: :created, location: @entry }
      else
        format.html { render action: "new" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    @entry = Entry.find(params[:id])

    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.json { render json: @entry, status: :created, location: @entry }
      else
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private
  
    def format_as_text entries
      #put logic here to create file with entries
      entries.map{|e| "***\n\n" + e.created_at.strftime("%F") + "\n\n" + e.content.gsub(%r{</?[^>]+?>}, '').gsub(%r{&nbsp;}, ' ')}.join("\n\n")
    end
    
    def format_as_html entries
      #put logic here to create file with entries
      string = "<html>\n\n<head></head>\n\n<body>\n\n"
      entries.each do |e| 
        string += "<div>\n\n" + e.created_at.strftime("%F") + "\n\n" + e.content + "\n\n</div>\n\n"
      end	
      string += "</body>\n\n</html>"
    end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  # GET /statistics
  # GET /statistics.json
  def index
    @statistics = Entry.user_entries(current_user.id).stats

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statistics }
    end
  end

  # GET /statistics/:type
  # GET /statistics/:type.json
  def show
    @statistic = Entry.user_entries(current_user.id).send(params[:type])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statistic }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  def readme
    render "readme"
  end
  
  # GET /users/current
  def current
    #entry = Entry.where("cast(created_at as text) like ? AND user_id = ?", "#{Time.zone.today}%", current_user.id).first
    render json: current_user
  end
  
  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        flash[:notice] = "Settings successfully updated!"
        format.html { render "edit" }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end   
end

app/helpers/application_helper.rb
module ApplicationHelper
  def parseForDate(date)
    date.utc.in_time_zone("Central Time (US & Canada)").strftime("%B %-d, %Y")
  end

  def parseForTime(date)
    date.utc.in_time_zone("Central Time (US & Canada)").strftime("%l:%M %p")
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    flash[:alert] = resource.errors.full_messages.first
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
  def monthnames
    months = Date::MONTHNAMES.dup
    months.delete(nil)
    months.map{|x| [x,Date::MONTHNAMES.index(x)]}
  end

  def date_searched? search
    search && search[:date] && !search[:date][:month].blank?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def possible_font_points
    %w{6 7 8 9 10 11 12 14 16 18 24 28 32 40 62}.map{|x| [x,x]}
  end
end

app/views/entries/_entry.html.erb
<article class="entry <%= entry.goal_completed %>">
  <header class="cf">
    <h4 class="left"><%= parseForDate(entry.created_at) %></h4>
    <span aria-hidden="true" class="goal-met help-item" id="GoalCompleted" data-icon="&#xe606;"></span>
  </header>
  <p>
    <%= entry.content.html_safe %>
  </p>
  <footer>
    <ul>
      <% entry.tags.each do |tag| %>
        <li><a href="/entries?search[q]=<%= tag.name %>" class="tag">#<%= tag.name %></a></li>
      <% end %>
    </ul>
  </footer>
  <div class="read-more-fade">&bull;&nbsp;&bull;&nbsp;&bull;</div>
</article>

app/views/entries/_textEditor.html.erb
<!--<div>-->
  <a onclick="popup('popUpDiv')" href="#"><button id = "opener" class="button left">New Entry</button></a>
<!--</div>-->
<%= form_for :entry, :url => {:action => :create}, :html => {:id => "createEntry"} do |f| %>
  <div id="blanket" style="display:none;"></div>
  <div id="popUpDiv" style="display:none;" class=fields>
    <%= f.text_area :content%>
  </div>
<% end %>

app/views/entries/_text_editor.html.erb
<%= form_tag('/entries', method: "post", id: "createEntry") do -%>
  <%= hidden_field_tag "entry[user_id]", current_user.id%>
  <div id="blanket" style="display:none;"></div>
  <div id="popUpDiv" data-updated-at="" data-bg-color-hex="" 
                     data-font-color-hex="" data-font-point="" 
                     data-created-at="" data-entry-id="" 
                     data-dist-count="" data-dist-time="" 
                     data-goal-completed="" style="display:none;">
    <%= text_area_tag "entry[content]"%>
    <div id="distractionAlerts" class="cf"></div>
  </div>
<% end %>

app/views/entries/index.html.erb
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<%= render 'text_editor' %>
<div id="dialog" title="What Format?"></div>
<section class="wrapper">
  <%= render "shared/navbar" %>
  <%= render "shared/header" %>
  <section class="entries">
    <%= render @entries %>
  </section>

  <% unless @entries.blank? %>
    <%= will_paginate @entries %>
  <% end %>
</section>

app/views/entries/index.js.erb
$('.entries').append('<%= escape_javascript render(@entries) %>');
<% if @entries.next_page %>
  $('.pagination').replaceWith('<%= escape_javascript will_paginate(@entries) %>');
<% else %>
  $('.pagination').remove();
<% end %>
updateExpandable();

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Journal Entry</h1>
<p><%= @entry.content %></p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>jurnl</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <link id="page_favicon" href="/assets/favicon.ico" rel="icon" type="image/x-icon" />
  </head>
  <body>
    <% if notice && notice != "Signed in successfully."%>
    <div class="notice"><p class="wrapper"><span aria-hidden="true" class="close" data-icon="&#xe607;"></span><%= notice %></p></div>
    <% end -%>

    <% if alert && alert != "You need to sign in or sign up before continuing."%>
    <div class="alert"><p class="wrapper"><span aria-hidden="true" class="close" data-icon="&#xe607;"></span><%= alert %></p></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<header class="main-header">
  <h1><%= link_to "jurnl", entries_path %></h1>
  <%= form_tag "/entries", method: "get", id: "search-form" do %>
    <%= submit_tag "Search", class: "button search-button" %>
    <%= link_to "javascript:void(0)", title: "Search by Month", class: "button icon", id: "date-icon" do %>
      <span aria-hidden="true" data-icon="&#xe604;"></span>
    <% end %>
    <div class="date-selects <%= "date-selects-hidden" unless date_searched? @search %>">
      <%= select_tag("search[date][month]", options_for_select(monthnames, @search.try(:[],:date).try(:[],:month)), prompt: "Month") %><%= select_tag("search[date][year]", options_for_select(YEARS, @search.try(:[],:date).try(:[],:year)), prompt: "Year", include_blank: false) %>
    </div>
    <%= text_field_tag "search[q]", @search.try(:[],:q) ,class: "search right" %>
  <% end %>
  <script type="text/javascript" src="/tiny_mce/tiny_mce.js"></script>
</header>

<% if date_searched? @search %>
  <div class="cf">
  <%= link_to "Previous Month", "javascript:void(0);", id: "prev-month"%>
  <%= link_to "Next Month", "javascript:void(0);", id: "next-month"%>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
  <section class="navigation">
    <a href="#" id = "opener" title="Edit Entry" class="button icon"><span aria-hidden="true" data-icon="&#xe600;"></a>
    <a href="/statistics" title="Statistics" class="button icon"><span aria-hidden="true" data-icon="&#xe601;"></span></a>
    <a href="/users/<%=current_user.id%>/edit" title="Settings" class="button icon"><span aria-hidden="true" data-icon="&#xe602;"></span></a>
    <a href="javascript:void(0);" title="Export" id="export" class="button icon"><span aria-hidden="true" data-icon="&#xe605;"></span></a>
    <a href="/users/readme" title="Help" id="help" class="button icon">?</a>
    <%= link_to :destroy_user_session, :class => "button icon", :title => "Sign Out", :method => :delete do %>
      <span aria-hidden="true" data-icon="&#xe603;">
    <% end %>
  </section>

app/views/shared/_navbar2.html.erb
  <section class="navigation">
    <a href="#" id = "opener" title="Edit Post" class="button icon"><span aria-hidden="true" data-icon="&#xe600;"></a>
    <a href="/statistics" title="Statistics" class="button icon"><span aria-hidden="true" data-icon="&#xe601;"></span></a>
    <a href="/users/<%=current_user.id%>/edit" title="Settings" class="button icon"><span aria-hidden="true" data-icon="&#xe602;"></span></a>
    <a href="/users/readme" title="Help" id="help" class="button icon">?</a>
    
    <%= link_to :destroy_user_session, :class => "button icon", :title => "Sign Out", :method => :delete do %>
      <span aria-hidden="true" data-icon="&#xe603;">
    <% end %>
  </section>

app/views/statistics/index.html.erb
<script type="text/javascript" src="tiny_mce/tiny_mce.js"></script>
<script type="text/javascript" src="https://www.google.com/jsapi"> </script>
<script> 
  google.load("visualization", "1", {packages:["corechart"]});
  google.setOnLoadCallback(drawChart);
</script>

<%= render 'entries/text_editor' %>
<section class="wrapper">
  <%= render "shared/navbar2" %>
  <%= render "shared/header" %>
  <section class="statistics">
    <div class="cf">
    <% @statistics.each do |key, value|  %>
      <div class="stat-box">
        <h2><%= key.to_s.titleize %></h2>
        <p>Minimum: <%= value[:min] %></p>
        <p>Maximum: <%= value[:max] %></p>
        <p>Average: <%= value[:avg] %></p>
      </div>
    <% end %>
    </div>
    <h2>Most Common Words:</h2>
    <img id="stats-loading" src="assets/stats-loading.gif"/>
  </section>
</section>

app/views/users/edit.html.erb
<script type="text/javascript" src="/jscolor/jscolor.js"> </script>

<%= render 'entries/text_editor' %>
<section class="wrapper">
  <%= render "shared/navbar2" %>
  <%= render "shared/header" %>
  <section class="settings">
    
      <h2>Settings</h2>
      <%= form_for @user, url: "/users/#{@user.id}", method: "put" do |f| %>
      <p>
        <%= f.label :bg_color_hex, "Entry Background Color:" %>
        <%= f.text_field :bg_color_hex, class: "color" %>
      </p>
     
      <p>
        <%= f.label :font_color_hex, "Entry Text Color:" %>
        <%= f.text_field :font_color_hex, class: "color" %>
      </p>
      
      <p>
        <%= f.label :font_point, "Entry Text Size:" %>
        <%= f.select :font_point, options_for_select(possible_font_points, @user.font_point) %>
      </p>
     
      <p>
        <span id="GoalDuration" class="help-item"><%= f.label :goal_duration, "Time Goal: (seconds)" %></span>
        <%= f.text_field :goal_duration %>
      </p>
      
      <p>
        <span id="GoalWordCount" class="help-item"><%= f.label :goal_word_count, "Word Count Goal:" %></span>
        <%= f.text_field :goal_word_count %>
      </p>

      <p>
        <span id="DistractionTime" class="help-item"><%= f.label :distraction_timeout, "Time Until Distracted: (seconds) " %></span>
        <%= f.text_field :distraction_timeout %>
      </p>
     
      <p>
        <%= f.submit :class => 'button', :value =>'Update settings' %>
      </p>
    <% end %>

</section>
</section>

app/views/users/readme.html.erb
<%= render 'entries/text_editor' %>
<section class="wrapper">
  <%= render "shared/navbar" %>
  <%= render "shared/header" %>
  <div class="cf"></div>
  <article class="entry">
    <h2>Welcome to your online jurnl. To get start, create an account on our homepage and start journaling! </h2>
  </article>

  <article class="entry">
    <h3>Create Journal Button <a href="#" id = "opener" class="button icon"><span aria-hidden="true" data-icon="&#xe600;"></a> </h3>
    <p>Click here to create a new post.</p>
  </article>

  <article class="entry">
    <h3>Journal Editor</h3>
    <p>The editor has basic editing and formatting functionality. </p>
  </article>

  <article class="entry">
    <h3>Statistics Button <a href="/statistics" title="Statistics" class="button icon"><span aria-hidden="true" data-icon="&#xe601;"></span></a> </h3>
    <p>Click here to view statistical information about your posts.
            <br />
            The statistics page allows you to see your minimum, average, and maximum values for word count, distraction count, 
            post duration, and words per minute of your posts. This page also includes a histogram of commonly used words in your posts. 
    </p>
  </article>

  <article class="entry">
    <h3>Settings Button <a href="/users/<%=current_user.id%>/edit" title="Settings" class="button icon"><span aria-hidden="true" data-icon="&#xe602;"></span></a></h3>
    <p>
            Click here to view various editable settings for the editor. The settings page allows you to change the default background color of the editor, the default text color, default text size, the time goal, word count goal, and distraction time.
            <ul>
            <li>Time goal is how many seconds you must type in order to complete your daily goal. </li>
            <li>Word count goal is how many words you must type in order to complete your daily goal.</li>
            <li>Time until distracted is the amount of time in seconds of you not typing until the editor counts a distraction. </li>
            <li>A distraction is a period of time you are not typing. Try closing other browser windows or programs that you would be likely to switch to when creating a journal entry. </li>
            </ul
    </p>
  </article>

  <article class="entry">
    <h3>Exporting <a href="javascript:void(0);" title="Export" id="export" class="button icon"><span aria-hidden="true" data-icon="&#xe605;"></span></a> </h3>
    <p>The export is only visible from your homepage. Click the export entry button to export your currently displayed posts to plain text or html. Keep in mind export only exports the currently displayed posts, if you want to export posts for last December, you will have to search for these posts first in order to display them. Try it out! </p>

  </article>

  <article class="entry">
    <h3>Search</h3>
    <p>By using the text field in the navbar, you can search for posts by keywords, tags, or date. The priority for searching is tag, date, keyword. This means that if a tags are found it will return those entries and discontinue searching.</p>
    <ul>
      <li>Tag Search: Search for any words that you specifically tagged in your entries.</li>
      <li>Keyword Search: Search for any words contained in your post.</li>
    </ul>

    <p> You can also browse the entries by month. To do this, click

    <a title="Search by Month" class="button icon", id="date-icon"> <span aria-hidden="true" data-icon="&#xe604;"></span></a>

    Then select the MONTH and or YEAR you would like to browse.

    Afterwards, you will see 
    <a id="prev-month" style="float:none;display:inline;margin-right:2px;">Previous Month</a>
    and
    <a id="next-month" style="float:none;display:inline;">Next Month</a>
    You can use these buttons to browse either next month's entries or the previous month's entries.
    </p>
  </article>

  <article class="entry">
    <h3>Sign-out Button <span class="button icon" aria-hidden="true" data-icon="&#xe603;"> </h3>
    <p>Click here to sign-out. </p>  
  </article>
</section>